// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13twRF_77Q6Z70G1D9VCP9cTDGH57aVE',
    appId: '1:971193695563:web:18f6ec61ebda877c443cce',
    messagingSenderId: '971193695563',
    projectId: 'core-venturo-f4e1c',
    authDomain: 'core-venturo-f4e1c.firebaseapp.com',
    storageBucket: 'core-venturo-f4e1c.appspot.com',
    measurementId: 'G-M5CT0GPWV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2juNA0wN0LVGGc-V0NrKvnhR2McXGJ0',
    appId: '1:971193695563:android:e944d6e21ff0e265443cce',
    messagingSenderId: '971193695563',
    projectId: 'core-venturo-f4e1c',
    storageBucket: 'core-venturo-f4e1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZY5A084dqE5mgcRiUD4q4ipxCr56WypQ',
    appId: '1:971193695563:ios:342d0fbee8203741443cce',
    messagingSenderId: '971193695563',
    projectId: 'core-venturo-f4e1c',
    storageBucket: 'core-venturo-f4e1c.appspot.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZY5A084dqE5mgcRiUD4q4ipxCr56WypQ',
    appId: '1:971193695563:ios:342d0fbee8203741443cce',
    messagingSenderId: '971193695563',
    projectId: 'core-venturo-f4e1c',
    storageBucket: 'core-venturo-f4e1c.appspot.com',
    iosBundleId: 'com.core.venturo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13twRF_77Q6Z70G1D9VCP9cTDGH57aVE',
    appId: '1:971193695563:web:dfe83b4e878953b4443cce',
    messagingSenderId: '971193695563',
    projectId: 'core-venturo-f4e1c',
    authDomain: 'core-venturo-f4e1c.firebaseapp.com',
    storageBucket: 'core-venturo-f4e1c.appspot.com',
    measurementId: 'G-QT4FKFP74P',
  );
}
